# Generated by Django 5.1.7 on 2025-03-28 23:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('average_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('average_sat', models.IntegerField(blank=True, null=True)),
                ('average_act', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('first_gen_status', models.BooleanField(default=False)),
                ('ethnicity', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenship_status', models.CharField(blank=True, choices=[('Citizen', 'Citizen'), ('Permanent Resident', 'Permanent Resident'), ('International', 'International')], max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('App', 'App')], default='Email', max_length=10)),
                ('fafsa_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Approved', 'Approved')], default='Not Started', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, related_name='counselor_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='counselor_users_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('coursework_difficulty', models.TextField(blank=True, null=True)),
                ('psat_score', models.IntegerField(blank=True, null=True)),
                ('sat_score', models.IntegerField(blank=True, null=True)),
                ('act_score', models.IntegerField(blank=True, null=True)),
                ('ap_scores', models.JSONField(blank=True, null=True)),
                ('ib_scores', models.JSONField(blank=True, null=True)),
                ('dual_enrollment_courses', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeAndCareerGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intended_major', models.CharField(blank=True, max_length=255, null=True)),
                ('career_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_college_type', models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private'), ('Community College', 'Community College'), ('Out-of-State', 'Out-of-State')], max_length=50, null=True)),
                ('study_abroad_interest', models.BooleanField(default=False)),
                ('honors_college_interest', models.BooleanField(default=False)),
                ('dream_schools', models.ManyToManyField(blank=True, related_name='dream_schools', to='counselor.college')),
                ('safety_schools', models.ManyToManyField(blank=True, related_name='safety_schools', to='counselor.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Not Started', max_length=50)),
                ('decision_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Early Action', 'Early Action'), ('Early Decision', 'Early Decision')], max_length=20, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('essay_link', models.URLField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Applied', 'Not Applied'), ('Pending', 'Pending'), ('Awarded', 'Awarded'), ('Rejected', 'Rejected')], default='Not Applied', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
