# Generated by Django 4.2.4 on 2025-04-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeapplication',
            name='essay_status',
        ),
        migrations.AddField(
            model_name='essaydraft',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counselor.collegeapplication'),
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='college',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='college',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='College',
        ),
    ]
