# Generated by Django 4.2.4 on 2025-03-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_message',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counselor.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.IntegerField(blank=True, choices=[(1, 'User'), (2, 'General Chat'), (3, 'Tutor Chat'), (4, 'Essay Chat')], default=1, null=True),
        ),
        migrations.DeleteModel(
            name='SentMessage',
        ),
    ]
