# Generated by Django 5.1.7 on 2025-03-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselor", "0002_remove_user_chat_message_message_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="salt",
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
