# Generated by Django 4.2.23 on 2025-07-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0002_alter_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
