# Generated by Django 5.1.7 on 2025-03-31 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0002_alter_award_name_alter_college_application_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeapplication',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 4, 30, 0, 17, 28, 136249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 4, 30, 0, 17, 28, 136855, tzinfo=datetime.timezone.utc)),
        ),
    ]
