# Generated by Django 4.2.23 on 2025-07-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0003_user_intro_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Citizen'), (2, 'Permanent Resident'), (3, 'Visa'), (4, 'International')], null=True),
        ),
    ]
