# Generated by Django 4.2.4 on 2025-04-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0003_alter_collegeapplication_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeapplication',
            name='major',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
