# Generated by Django 5.1.7 on 2025-03-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselor", "0003_user_salt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="award",
            new_name="awards",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="extracurricular",
            new_name="extracurriculars",
        ),
        migrations.AddField(
            model_name="course",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Regular"), (2, "Honors"), (3, "AP"), (4, "IB")],
                default=9,
                null=True,
            ),
        ),
    ]
