# Generated by Django 4.2.23 on 2025-07-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0004_alter_user_citizenship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_gen',
            field=models.IntegerField(blank=True, choices=[(1, 'Not First Gen'), (2, 'First Gen')], null=True),
        ),
    ]
