# Generated by Django 5.1.7 on 2025-03-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselor", "0004_rename_award_user_awards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes"),
        ),
    ]
