# Generated by Django 5.1.7 on 2025-04-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0003_alter_collegeapplication_deadline_and_more'),
        ('counselor', '0005_alter_user_resume'),
    ]

    operations = [
    ]
