# Generated by Django 5.2 on 2025-07-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0005_alter_user_first_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro_message',
            field=models.TextField(blank=True, default='Welcome to Counselor Pablo College Counseling. Edit your profile to see your personalized intro message.', null=True),
        ),
    ]
