# Generated by Django 4.2.4 on 2025-04-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0005_alter_user_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ap_scores',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dual_enrollment_courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='freshman_sem1_gpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='freshman_sem2_gpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ib_scores',
        ),
        migrations.RemoveField(
            model_name='user',
            name='junior_sem1_gpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='junior_sem2_gpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='senior_sem1_gpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='senior_sem2_gpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sophomore_sem1_gpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sophomore_sem2_gpa',
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ap_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='grades',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ib_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sem1_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sem2_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
