# Generated by Django 5.2 on 2025-07-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0006_alter_user_intro_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
