# Generated by Django 5.2 on 2025-07-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0007_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(9, 'Freshman'), (10, 'Sophomore'), (11, 'Junior'), (12, 'Senior')], null=True),
        ),
    ]
