# Generated by Django 5.1.7 on 2025-04-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0006_remove_course_description_remove_user_ap_scores_and_more'),
        ('counselor', '0007_alter_award_name_alter_college_application_platform_and_more'),
    ]

    operations = [
    ]
