# Generated by Django 4.2.4 on 2025-04-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0007_extracurricular_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Citizen'), (2, 'Permanent Resident'), (3, 'Visa'), (4, 'International')], default=1, null=True),
        ),
    ]
