# Generated by Django 5.1.7 on 2025-04-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0008_merge_20250417_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricular',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Academic'), (2, 'Athletics: Club'), (3, 'Athletics: JV/Varsity'), (4, 'Career Oriented'), (5, 'Community Service (Volunteer)'), (6, 'Computer/Technology'), (7, 'Cultural'), (8, 'Dance'), (9, 'Debate/Speech'), (10, 'Environmental'), (11, 'Family Responsibilities'), (12, 'Foreign Exchange'), (13, 'Foreign Language'), (14, 'Internship'), (15, 'Journalism/Publication'), (16, 'Junior ROTC'), (17, 'LGBTQIA+'), (18, 'Music: Instrumental'), (19, 'Music: Vocal'), (20, 'Religious'), (21, 'Research'), (22, 'Robotics'), (23, 'School Spirit'), (24, 'Science/Math'), (25, 'Social Justice'), (26, 'Theater/Drama'), (27, 'Work (Paid)'), (28, 'Other Club/Activity')], default=9, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='application_platform',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
