# Generated by Django 5.1.7 on 2025-04-27 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0008_alter_user_citizenship_status'),
        ('counselor', '0009_extracurricular_type_and_more'),
    ]

    operations = [
    ]
