# Generated by Django 5.1.7 on 2025-04-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0010_merge_20250427_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='average_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
