# Generated by Django 5.1.7 on 2025-04-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0011_alter_college_average_gpa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
