# Generated by Django 5.1.7 on 2025-04-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0012_delete_message'),
    ]

    operations = [
    ]
