# Generated by Django 5.1.7 on 2025-04-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0002_remove_collegeapplication_essay_status_and_more'),
        ('counselor', '0004_alter_collegeapplication_major'),
        ('counselor', '0015_alter_user_email'),
    ]

    operations = [
    ]
