# Generated by Django 5.1.7 on 2025-04-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0016_merge_20250430_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeapplication',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
